export const vehicles = [
  {
    brand: "Audi",
    rating: "4.96",
    reviews: "672 reviews",
    model: "A3 1.6 TDI S line",
    location: "Manchester, England",
    mileage: "25,100 miles",
    transmission: "Automatic",
    fuel: "Diesel",
    seats: "5 seats",
    price: "498.25",
    image: "/car21.jpg"
  },
  {
    brand: "Volvo",
    rating: "4.83",
    reviews: "521 reviews",
    model: "S60 D4 R-Design",
    location: "New South Wales, Australia",
    mileage: "19,800 miles",
    transmission: "Automatic",
    fuel: "Diesel",
    seats: "5 seats",
    price: "450.00",
    image: "/car26.jpg"
  },
  {
    brand: "Mercedes-Benz",
    rating: "4.92",
    reviews: "732 reviews",
    model: "C220d AMG Line",
    location: "London, UK",
    mileage: "31,200 miles",
    transmission: "Automatic",
    fuel: "Diesel",
    seats: "5 seats",
    price: "530.75",
    image: "/car28.jpeg"
  },
  {
    brand: "Jaguar",
    rating: "4.75",
    reviews: "468 reviews",
    model: "XE 2.0d R-Sport",
    location: "Los Angeles, USA",
    mileage: "22,500 miles",
    transmission: "Automatic",
    fuel: "Diesel",
    seats: "5 seats",
    price: "510.50",
    image: "/car30.jpg"
  },
  {
    brand: "Volkswagen",
    rating: "4.68",
    reviews: "388 reviews",
    model: "Golf GTD 2.0 TDI",
    location: "Berlin, Germany",
    mileage: "27,400 miles",
    transmission: "Manual",
    fuel: "Diesel",
    seats: "5 seats",
    price: "460.00",
    image: "/car31.jpg"
  },
  {
    brand: "Lexus",
    rating: "4.90",
    reviews: "503 reviews",
    model: "IS 300h F Sport",
    location: "Tokyo, Japan",
    mileage: "20,000 miles",
    transmission: "Automatic",
    fuel: "Hybrid",
    seats: "5 seats",
    price: "520.00",
    image: "/car38.jpg"
  },
  {
    brand: "Toyota",
    rating: "4.82",
    reviews: "689 reviews",
    model: "Camry XSE V6",
    location: "Toronto, Canada",
    mileage: "24,700 miles",
    transmission: "Automatic",
    fuel: "Petrol",
    seats: "5 seats",
    price: "480.25",
    image: "/car37.jpg"
  },
  {
    brand: "BMW",
    rating: "4.95",
    reviews: "815 reviews",
    model: "320i M Sport",
    location: "Paris, France",
    mileage: "21,000 miles",
    transmission: "Automatic",
    fuel: "Petrol",
    seats: "5 seats",
    price: "550.00",
    image: "/car39.jpg"
  }
];
